
CREATE DATABASE crud3;
use crud3;
CREATE TABLE users(
    id INT(11) NOT NULL,
    nombre VARCHAR(45)NOT NULL,
    username VARCHAR(45)NOT NULL,
    numero VARCHAR(45)NOT NULL
);
ALTER TABLE users
    ADD PRIMARY KEY(id);

ALTER TABLE users
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

CREATE TABLE music(
    id INT(11) NOT NULL,
    title VARCHAR(45) NOT NULL,
    autor VARCHAR(45) NOT NULL,
    link VARCHAR(80) NOT NULL,
    hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    users_id INT(11),
    CONSTRAINT fk_users_id  FOREIGN KEY(users_id) REFERENCES users(id)
);

ALTER TABLE music
    ADD PRIMARY KEY (id);
ALTER TABLE music
    MODIFY id INT(11)NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

SHOW TABLES;

